### ISSUE TITLE
Can't find the VB6 Template

### ISSUE THREAD

**Issue by PabloInNz** [hurcane/Microsoft.InteropFormTools.InteropFormProxyGenerator#1]
Is the Vb6 Interop UserControl template available with this method ? I have donwloaded the interop ToolKit and installed and compiled and run the wsix, but I don't see the template anywhere when I fire up VS 2015 (Community). Any ideas ?  Thanks Paul

**Comment by hurcane** [comment]
I don't think the template is part of the ported VSIX. Only the code related to the "Generate" custom menu item was included. Is the custom menu option showing up? I'm not familiar with the community edition, as I use a professional edition through my MSDN subscription.

**Comment by PabloInNz** [comment]
Thanks for the speedy reply. I've sorted it now. I needed to copy the zip files from the default install directory for the Interop toolkit to the Templates directory C:\Users<username>\Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual Basic

Glad to see I'm not the only one who is still stuck with legacy Vb6 code and using VS 2015 !

**Comment by NoteToSelfFindGoodNickname** [comment]
PablonNz Which zip files do you mean?
I found only 1 zip file:
\Source\Source.zip

I have copied it to 
C:\Users\MyUser\Documents\Visual Studio 2019\Templates\ProjectTemplates\Visual Basic\Source.zip

But I do not see a template when I open up VS2019.

Where should that be located, please?

In this screen?

![wegs1](https://user-images.githubusercontent.com/29504639/183461907-0002981a-57ae-4a1c-a7c5-4d64a22755c5.png)

**Comment by hurcane** [comment]
I think the templates would be found in this folder (assuming the default installation location):
C:\Program Files (x86)\Microsoft Visual Basic Power Packs\Interop Forms Toolkit 2.1\Setup\User

The zip files in that folder look to be the templates.
