### ISSUE TITLE
Open Solution

### ISSUE THREAD

**Issue by stefanofalasca** [hurcane/Microsoft.InteropFormTools.InteropFormProxyGenerator#2]
Hi, that is great project, but I am not able to load solution. The solution is empty with no files loaded. It has an error during loading. I am using vs2015. That is message showed in output window:

C:\Interop Form Kit\Source\Microsoft.InteropFormTools.InteropFormProxyGenerator-master\Microsoft.InteropFormTools.InteropFormProxyGenerator-master\Microsoft.InteropFormTools.InteropFormProxyGenerator\Microsoft.InteropFormTools.InteropFormProxyGenerator.vbproj : error  : impossibile valutare i metadati dell'elemento "%(FullPath)". Impossibile applicare i metadati dell'elemento "%(FullPath)" al percorso "obj\Debug\Microsoft.InteropFormTools.InteropFormProxyGenerator.dll". C:\Interop Form Kit\Source\Microsoft.InteropFormTools.InteropFormProxyGenerator-master\Microsoft.InteropFormTools.InteropFormProxyGenerator-master\Microsoft.InteropFormTools.InteropFormProxyGenerator\obj\Debug\Microsoft.InteropFormTools.InteropFormProxyGenerator.dll  C:\Program Files\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets

Any idea ?

**Comment by hurcane** [comment]
I'm not what exactly that error message means. You do have Interop Forms Toolkit 2.1 already installed?

**Comment by stefanofalasca** [comment]
I solved thanks 

Inviato da iPhone
