### ISSUE TITLE
Not seeing extension in the Marketplace

### ISSUE THREAD

**Issue by bzuillsmith** [hurcane/Microsoft.InteropFormTools.InteropFormProxyGenerator#4]
I'm using the latest version of VS 2017. I'm not seeing this extension in the marketplace. What's it called? Is it supposed to be 'Microsoft Interop Form Tools Proxy Generator'?

**Comment by hurcane** [comment]
This extension is not in the public marketplace and it does not have any binaries to download. You can download the source, build it, then run the VSIX to add it to your Visual Studio installation. For my team, we put the VSIX file on a shared folder.
